export const SUBSCRIPTIONS_FETCH_REQUEST = 'SUBSCRIPTIONS_FETCH_REQUEST';
export const SUBSCRIPTIONS_FETCH_SUCCESS = 'SUBSCRIPTIONS_FETCH_SUCCESS';
export const SUBSCRIPTIONS_FETCH_FAIL = 'SUBSCRIPTIONS_FETCH_FAIL';

export const SUBSCRIPTIONS_FEED_REQUEST = 'SUBSCRIPTIONS_FEED_REQUEST';
export const SUBSCRIPTIONS_FEED_SUCCESS = 'SUBSCRIPTIONS_FEED_SUCCESS';
export const SUBSCRIPTIONS_FEED_FAIL = 'SUBSCRIPTIONS_FEED_FAIL';
